// APP STATUS //
export const API_REQUEST = 'API_REQUEST';
export const API_REQUEST_SUCCESS = 'API_REQUEST_SUCCESS';
export const API_REQUEST_FAILURE = 'API_REQUEST_FAILURE';
export const API_REQUEST_NETWORK_ERROR = 'API_REQUEST_NETWORK_ERROR';

export const RESET_MESSAGE_STATE = 'RESET_MESSAGE_STATE';
export const SEND_ERROR_MESSAGE = 'SEND_ERROR_MESSAGE';

export const SHOW_NETWORK_ERROR = 'SEND_NETWORK_ERROR';
export const CLEAR_NETWORK_ERROR = 'CLEAR_NETWORK_ERROR';


// USER AUTH //
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';


// DATA API //
export const GET_POLITICIANS = 'GET_POLITICIANS';
export const GET_POLITICIANS_SUCCESS = 'GET_POLITICIANS_SUCCESS';
export const GET_POLITICIANS_FAILURE = 'GET_POLITICIANS_FAILURE';