export const API_REQUEST = 'API_REQUEST';
export const API_REQUEST_SUCCESS = 'API_REQUEST_SUCCESS';
export const API_REQUEST_FAILURE = 'API_REQUEST_FAILURE';
export const API_REQUEST_NETWORK_ERROR = 'API_REQUEST_NETWORK_ERROR';

export const GET_POLITICIANS = 'GET_POLITICIANS';
export const GET_POLITICIANS_SUCCESS = 'GET_POLITICIANS_SUCCESS';
export const GET_POLITICIANS_FAILURE = 'GET_POLITICIANS_FAILURE';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';
export const RESET_MESSAGE_STATE = 'RESET_MESSAGE_STATE';